# Site settings
title: Guillermo
email: guillermos2007@gmail.com
description:

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://guillermosalazar.me" # the base hostname & protocol for your site
twitter_username: gsala2011
github_username:  guillermo-salazar
# Build settings
markdown: kramdown
